Documenter/Models/Client.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Documenter.Models
{
    public class Client
    {
        private IList<Document> _documents;
        public virtual Guid Id { get; set; }
        public virtual string Username { get; set; }
        public virtual string PasswordHash { get; set; }
        public virtual IList<Document> Documents {
            get
            {
                return _documents ?? (_documents = new List<Document>());
            }
            set
            {
                _documents = value;
            }
        }

    }
}

Documenter/Models/Document.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Documenter.Models
{
    public class Document
    {
        public virtual Guid Id { get; set; }
        public virtual string Name { get; set; }
        public virtual string RealName { get; set; }
        public virtual DateTime Date { get; set; }
        public virtual Client Autor { get; set; }
        public virtual byte[] Data { get; set; }
    }
}

Documenter/Models/Helpers/ClientLogOn.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Documenter.Models.Helpers
{
    public class ClientLogOn
    {
        [StringLength(255, MinimumLength = 1, ErrorMessage = "Требуется ввести от 1 до 255 символов!")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Требуется логин!")]
        [DisplayName("Логин")]
        public string Username { get; set; }
        [StringLength(255, MinimumLength = 1, ErrorMessage = "Требуется ввести от 1 до 255 символов!")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Требуется пароль!")]
        [DisplayName("Пароль")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}

Documenter/Models/Helpers/DocumentAdd.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Documenter.Models.Helpers
{
    public class DocumentAdd
    {
        [DisplayName("Имя документа")]
        [Required(AllowEmptyStrings =false, ErrorMessage ="Требуется имя документа!")]
        [StringLength(255, MinimumLength =1, ErrorMessage = "Требуется назание от 1 до 255 символов!")]
        
        public string Name { get; set; }
        [DisplayName("Файл")]
        [Required(ErrorMessage ="Требуется файл!")]
        public string Upload_file { get; set; }
    }
}

Documenter/Controllers/AuthController.cs
using Documenter.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Documenter.Controllers
{
    public class AuthController : Controller
    {
        public ActionResult LogOn()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LogOn(Documenter.Models.Helpers.ClientLogOn model, string returnUrl)
        {
            string decodedUrl = "";
            if (!string.IsNullOrWhiteSpace(returnUrl))
                decodedUrl = Server.UrlDecode(returnUrl);
            if (ModelState.IsValid)
            {
                var repository = new ClientRepository();
                var client = repository.GetByUserName(model.Username)
                    .FirstOrDefault(it => model.Password == it.PasswordHash);
                if (client != null)
                {
                    FormsAuthentication.SetAuthCookie(client.Id.ToString(), true);
                    if (Url.IsLocalUrl(decodedUrl))
                    {
                        return Redirect(decodedUrl);
                    }
                    else
                    {
                        return RedirectToAction("Index", "Home");
                    }
                }
                ModelState.AddModelError("", "Неверный логин/пароль");
            }
            else
            {
                ModelState.AddModelError("", "Некорректное заполнение полей!");
            }
            return View();
        }

        public ActionResult LogOut(string returnUrl)
        {
            string decodedUrl = "";
            if (!string.IsNullOrWhiteSpace(returnUrl))
                decodedUrl = Server.UrlDecode(returnUrl);
            FormsAuthentication.SignOut();
            if (Url.IsLocalUrl(decodedUrl))
            {
                return Redirect(decodedUrl);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }
    }
}

Documenter/Controllers/DocumentsController.cs
using Documenter.Models;
using Documenter.Repositories;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Documenter.Controllers
{
    [Authorize]
    public class DocumentsController : Controller
    {
        public ActionResult Index()
        {
            var documentRepository = new DocumentRepository();
            var documents = new List<Document>();
            ViewBag.Documents = documents.Concat(documentRepository.GetOrderedBy("Name"));
            return View();
        }
        public ActionResult Add()
        {
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Add(string name, HttpPostedFileBase Upload_file)
        {
            if (Upload_file != null)
            {
                var realName = Path.GetFileName(Upload_file.FileName);
                if(!Directory.Exists(Server.MapPath("~/Files/")))
                {
                    Directory.CreateDirectory(Server.MapPath("~/Files/"));
                }
                if (ModelState.IsValid)
                {
                    var clientRepository = new ClientRepository();
                    var client = clientRepository.GetByGuid(Guid.Parse(User.Identity.Name));
                    var document = new Document()
                    {
                        Id = new Guid(),
                        Name = name,
                        RealName = realName,
                        Autor = client,
                        Date = DateTime.Now,
                        Data = new byte[Upload_file.InputStream.Length]
                    };

                    var documentRepository = new DocumentRepository();
                    documentRepository.Add(document);

                    Upload_file.InputStream.Read(document.Data, 0, (int)Upload_file.InputStream.Length);
                    Upload_file.SaveAs(Server.MapPath($"~/Files/{document.Id.ToString()}"));
                }
                else
                {
                    ModelState.AddModelError("", "Неверное заполнение полей!");
                }

                ViewBag.FileStatus = "Файл успешно загружен!";
            }
            return RedirectToAction("Index");
            //return View("Index");
        }
        public ActionResult All()
        {
            return RedirectToAction("Index");
        }

        public ActionResult Order(string orderby)
        {
            var documentRepository = new DocumentRepository();
            return PartialView(documentRepository.GetOrderedBy(orderby));
        }

        public FileResult Download(string file_guid)
        {
            var documentRepository = new DocumentRepository();
            var document = documentRepository.GetByGuid(Guid.Parse(file_guid));
            if (document != null)
            {
                if (!System.IO.File.Exists(Server.MapPath("~/Files/") + document.Id.ToString()))
                {
                    System.IO.File.WriteAllBytes(Server.MapPath("~/Files/") + document.Id.ToString(), document.Data);
                }
                return File(Server.MapPath("~/Files/") + document.Id.ToString(), "application/octet-stream", document.RealName);
            }
            return null;
        }
    }
}

Documenter/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Documenter.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Documenter/Views/Documents/Add.cshtml
@model Documenter.Models.Helpers.DocumentAdd

@using (Html.BeginForm("Add", "Documents", FormMethod.Post, new {enctype = "multipart/form-data" }))
{
    <div class="form-horizontal">
        @Html.ValidationSummary(true)
        <div class="form-group">
            @Html.LabelFor(model => model.Name)
            <div class="form-horizontal">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Файл")
            <div class="form-horizontal">
                @Html.EditorFor(model => model.Upload_file, new { htmlAttributes = new {@class = "form-control", @type = "file"}})
                @Html.ValidationMessageFor(model => model.Upload_file, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <input type="submit" value="Отправить" class="btn btn-default" />
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10 text-success">
                @ViewBag.FileStatus
            </div> 
        </div>
    </div>
}

Documenter/Views/Documents/All.cshtml
<div id="alldocuments">
   @Html.Partial("Order")
</div>

Documenter/Views/Documents/Index.cshtml
@{
    ViewBag.Title = "Работа с документами";
}
<div class="jumbotron">
    <h2>Работа с документами</h2>
    <div class="form-horizontal">
        <div class="form-group">
            @Html.Partial("Add")
        </div>
        <br />
        <div class="form-group">
            @Html.Partial("All")
        </div>
    </div>
</div>

@section Scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}

Documenter/Views/Documents/Order.cshtml
@model IEnumerable<Documenter.Models.Document>
<table class="table table-condensed table-hover">
    <thead>
        <tr>
            <th>
                @Ajax.ActionLink("Имя", "Order", new { orderby = "Name" }, new AjaxOptions { UpdateTargetId = "alldocuments" })
            </th>
            <th>
                @Ajax.ActionLink("Файл", "Order", new { orderby = "RealName" }, new AjaxOptions { UpdateTargetId = "alldocuments" })
            </th>
            <th>
                @Ajax.ActionLink("Создан", "Order", new { orderby = "Date" }, new AjaxOptions { UpdateTargetId = "alldocuments" })
            </th>
            <th>
                @Ajax.ActionLink("Владелец", "Order", new { orderby = "Autor" }, new AjaxOptions { UpdateTargetId = "alldocuments" })
            </th>
            <th>
                Скачать
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model ?? ViewBag.Documents)
        {
            <tr>
                @{
                    string name = (item.Name.Length > 30 ? item.Name.Substring(0, 30) + "..." : item.Name);
                    string realname = (item.RealName.Length > 30 ? item.RealName.Substring(0, 30) + "..." : item.RealName);
                    string date = item.Date.ToString();
                    string autor = item.Autor.Username;
                }
                <td>@name</td>
                <td>@realname</td>
                <td>@date</td>
                <td>@autor</td>
                <td>
                    <a href="@Url.Action("Download", "Documents", new { file_guid = item.Id.ToString() })">
                        <img src="~/Images/download_btn.ico" height="20%" />
                    </a>
                    
                </td>
            </tr>
        }
    </tbody>
</table>

Documenter/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Главная";
}

<div class="jumbotron">
    <h1>Documenter</h1>
    <p class="lead">Documenter это задание для ЭЛМЫ. Возьмите меня сеньёром. Плес.</p>
    @if (User.Identity.IsAuthenticated)
    {
        <p>@Html.ActionLink("Начать работу »", "Index", "Documents", new { area = "" }, new { @class = "btn btn-primary btn-lg" })</p>
    }
    else
    {
        <p>@Html.ActionLink("Войти для работы »", "Index", "Documents", new { area = "" }, new { @class = "btn btn-primary btn-lg" })</p>
    }
</div>

Documenter/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – Documenter</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Documenter", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Начать работу", "Index", "Documents")</li>
                        <li>@Html.ActionLink("Выйти", "LogOut", "Auth")</li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Войти для работы", "LogOn", "Auth")</li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – IWannaBeSenior LLC</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryval")

    @Scripts.Render("~/scripts/jquery-3.3.1.js")
    @Scripts.Render("~/scripts/jquery.unobtrusive-ajax.js")
    @RenderSection("scripts", required: false)
</body>
</html>